app:
    show_version_update: true
    version_check_url: https://raw.githubusercontent.com/gotoailab/trendhub/refs/heads/master/version
crawler:
    default_proxy: http://127.0.0.1:10086
    enable_crawler: true
    request_interval: 1000
    use_proxy: false
notification:
    batch_send_interval: 3
    dingtalk_batch_size: 20000
    enable_notification: true
    feishu_batch_size: 29000
    feishu_message_separator: ━━━━━━━━━━━━━━━━━━━
    message_batch_size: 4000
    push_window:
        enabled: true
        once_per_day: true
        push_record_retention_days: 7
        time_range:
            end: "22:00"
            start: "20:00"
    webhooks:
        dingtalk_url: ""
        email_from: admin
        email_password: admin123Abc==
        email_smtp_port: ""
        email_smtp_server: ""
        email_to: ""
        feishu_url: ""
        ntfy_server_url: https://ntfy.sh
        ntfy_token: ""
        ntfy_topic: ""
        telegram_bot_token: ""
        telegram_chat_id: ""
        wework_url: ""
        bark_server_url: "https://api.day.app"
        bark_device_key: ""
        wps_webhook_url: ""
platforms:
    - id: toutiao
      name: 今日头条
    - id: baidu
      name: 百度热搜
    - id: wallstreetcn-hot
      name: 华尔街见闻
    - id: thepaper
      name: 澎湃新闻
    - id: bilibili-hot-search
      name: bilibili 热搜
    - id: cls-hot
      name: 财联社热门
    - id: ifeng
      name: 凤凰网
    - id: tieba
      name: 贴吧
    - id: weibo
      name: 微博
    - id: douyin
      name: 抖音
    - id: zhihu
      name: 知乎
report:
    mode: daily
    rank_threshold: 5
weight:
    frequency_weight: 0.3
    hotness_weight: 0.1
    rank_weight: 0.6
